(cl:defpackage ros_learning-msg
  (:use )
  (:export
   "<LANDINGACTION>"
   "LANDINGACTION"
   "<LANDINGACTIONFEEDBACK>"
   "LANDINGACTIONFEEDBACK"
   "<LANDINGACTIONGOAL>"
   "LANDINGACTIONGOAL"
   "<LANDINGACTIONRESULT>"
   "LANDINGACTIONRESULT"
   "<LANDINGFEEDBACK>"
   "LANDINGFEEDBACK"
   "<LANDINGGOAL>"
   "LANDINGGOAL"
   "<LANDINGRESULT>"
   "LANDINGRESULT"
  ))

