; Auto-generated. Do not edit!


(cl:in-package ros_learning-msg)


;//! \htmlinclude LandingFeedback.msg.html

(cl:defclass <LandingFeedback> (roslisp-msg-protocol:ros-message)
  ((current_z
    :reader current_z
    :initarg :current_z
    :type cl:float
    :initform 0.0))
)

(cl:defclass LandingFeedback (<LandingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LandingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LandingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_learning-msg:<LandingFeedback> is deprecated: use ros_learning-msg:LandingFeedback instead.")))

(cl:ensure-generic-function 'current_z-val :lambda-list '(m))
(cl:defmethod current_z-val ((m <LandingFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_learning-msg:current_z-val is deprecated.  Use ros_learning-msg:current_z instead.")
  (current_z m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LandingFeedback>) ostream)
  "Serializes a message object of type '<LandingFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_z))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LandingFeedback>) istream)
  "Deserializes a message object of type '<LandingFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_z) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LandingFeedback>)))
  "Returns string type for a message object of type '<LandingFeedback>"
  "ros_learning/LandingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LandingFeedback)))
  "Returns string type for a message object of type 'LandingFeedback"
  "ros_learning/LandingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LandingFeedback>)))
  "Returns md5sum for a message object of type '<LandingFeedback>"
  "d6cd43679fdc1814ce8efd082df37054")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LandingFeedback)))
  "Returns md5sum for a message object of type 'LandingFeedback"
  "d6cd43679fdc1814ce8efd082df37054")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LandingFeedback>)))
  "Returns full string definition for message of type '<LandingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback: 当前高度~%float32 current_z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LandingFeedback)))
  "Returns full string definition for message of type 'LandingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback: 当前高度~%float32 current_z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LandingFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LandingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LandingFeedback
    (cl:cons ':current_z (current_z msg))
))
