; Auto-generated. Do not edit!


(cl:in-package ros_learning-msg)


;//! \htmlinclude LandingResult.msg.html

(cl:defclass <LandingResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass LandingResult (<LandingResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LandingResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LandingResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_learning-msg:<LandingResult> is deprecated: use ros_learning-msg:LandingResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <LandingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_learning-msg:success-val is deprecated.  Use ros_learning-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LandingResult>) ostream)
  "Serializes a message object of type '<LandingResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LandingResult>) istream)
  "Deserializes a message object of type '<LandingResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LandingResult>)))
  "Returns string type for a message object of type '<LandingResult>"
  "ros_learning/LandingResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LandingResult)))
  "Returns string type for a message object of type 'LandingResult"
  "ros_learning/LandingResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LandingResult>)))
  "Returns md5sum for a message object of type '<LandingResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LandingResult)))
  "Returns md5sum for a message object of type 'LandingResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LandingResult>)))
  "Returns full string definition for message of type '<LandingResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result: 最终是否成功~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LandingResult)))
  "Returns full string definition for message of type 'LandingResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result: 最终是否成功~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LandingResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LandingResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LandingResult
    (cl:cons ':success (success msg))
))
