// Generated by gencpp from file ros_learning/LandingGoal.msg
// DO NOT EDIT!


#ifndef ROS_LEARNING_MESSAGE_LANDINGGOAL_H
#define ROS_LEARNING_MESSAGE_LANDINGGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_learning
{
template <class ContainerAllocator>
struct LandingGoal_
{
  typedef LandingGoal_<ContainerAllocator> Type;

  LandingGoal_()
    : target_x(0.0)
    , target_y(0.0)
    , target_z(0.0)  {
    }
  LandingGoal_(const ContainerAllocator& _alloc)
    : target_x(0.0)
    , target_y(0.0)
    , target_z(0.0)  {
  (void)_alloc;
    }



   typedef float _target_x_type;
  _target_x_type target_x;

   typedef float _target_y_type;
  _target_y_type target_y;

   typedef float _target_z_type;
  _target_z_type target_z;





  typedef boost::shared_ptr< ::ros_learning::LandingGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_learning::LandingGoal_<ContainerAllocator> const> ConstPtr;

}; // struct LandingGoal_

typedef ::ros_learning::LandingGoal_<std::allocator<void> > LandingGoal;

typedef boost::shared_ptr< ::ros_learning::LandingGoal > LandingGoalPtr;
typedef boost::shared_ptr< ::ros_learning::LandingGoal const> LandingGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_learning::LandingGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_learning::LandingGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_learning::LandingGoal_<ContainerAllocator1> & lhs, const ::ros_learning::LandingGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_x == rhs.target_x &&
    lhs.target_y == rhs.target_y &&
    lhs.target_z == rhs.target_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_learning::LandingGoal_<ContainerAllocator1> & lhs, const ::ros_learning::LandingGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_learning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_learning::LandingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_learning::LandingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_learning::LandingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_learning::LandingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_learning::LandingGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_learning::LandingGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_learning::LandingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0889c97caa2572f42484385187224bc4";
  }

  static const char* value(const ::ros_learning::LandingGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0889c97caa2572f4ULL;
  static const uint64_t static_value2 = 0x2484385187224bc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_learning::LandingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_learning/LandingGoal";
  }

  static const char* value(const ::ros_learning::LandingGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_learning::LandingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal: 目标位置 (X, Y)\n"
"float32 target_x\n"
"float32 target_y\n"
"float32 target_z\n"
;
  }

  static const char* value(const ::ros_learning::LandingGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_learning::LandingGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_x);
      stream.next(m.target_y);
      stream.next(m.target_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandingGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_learning::LandingGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_learning::LandingGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_x: ";
    Printer<float>::stream(s, indent + "  ", v.target_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_y: ";
    Printer<float>::stream(s, indent + "  ", v.target_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_z: ";
    Printer<float>::stream(s, indent + "  ", v.target_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_LEARNING_MESSAGE_LANDINGGOAL_H
