// Generated by gencpp from file ros_learning/LandingFeedback.msg
// DO NOT EDIT!


#ifndef ROS_LEARNING_MESSAGE_LANDINGFEEDBACK_H
#define ROS_LEARNING_MESSAGE_LANDINGFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_learning
{
template <class ContainerAllocator>
struct LandingFeedback_
{
  typedef LandingFeedback_<ContainerAllocator> Type;

  LandingFeedback_()
    : current_z(0.0)  {
    }
  LandingFeedback_(const ContainerAllocator& _alloc)
    : current_z(0.0)  {
  (void)_alloc;
    }



   typedef float _current_z_type;
  _current_z_type current_z;





  typedef boost::shared_ptr< ::ros_learning::LandingFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_learning::LandingFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LandingFeedback_

typedef ::ros_learning::LandingFeedback_<std::allocator<void> > LandingFeedback;

typedef boost::shared_ptr< ::ros_learning::LandingFeedback > LandingFeedbackPtr;
typedef boost::shared_ptr< ::ros_learning::LandingFeedback const> LandingFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_learning::LandingFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_learning::LandingFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_learning::LandingFeedback_<ContainerAllocator1> & lhs, const ::ros_learning::LandingFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_z == rhs.current_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_learning::LandingFeedback_<ContainerAllocator1> & lhs, const ::ros_learning::LandingFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_learning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_learning::LandingFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_learning::LandingFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_learning::LandingFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_learning::LandingFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_learning::LandingFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_learning::LandingFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_learning::LandingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6cd43679fdc1814ce8efd082df37054";
  }

  static const char* value(const ::ros_learning::LandingFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6cd43679fdc1814ULL;
  static const uint64_t static_value2 = 0xce8efd082df37054ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_learning::LandingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_learning/LandingFeedback";
  }

  static const char* value(const ::ros_learning::LandingFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_learning::LandingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback: 当前高度\n"
"float32 current_z\n"
;
  }

  static const char* value(const ::ros_learning::LandingFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_learning::LandingFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandingFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_learning::LandingFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_learning::LandingFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "current_z: ";
    Printer<float>::stream(s, indent + "  ", v.current_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_LEARNING_MESSAGE_LANDINGFEEDBACK_H
