// Auto-generated. Do not edit!

// (in-package ros_learning.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LandingFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_z = null;
    }
    else {
      if (initObj.hasOwnProperty('current_z')) {
        this.current_z = initObj.current_z
      }
      else {
        this.current_z = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LandingFeedback
    // Serialize message field [current_z]
    bufferOffset = _serializer.float32(obj.current_z, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LandingFeedback
    let len;
    let data = new LandingFeedback(null);
    // Deserialize message field [current_z]
    data.current_z = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ros_learning/LandingFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd6cd43679fdc1814ce8efd082df37054';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback: 当前高度
    float32 current_z
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LandingFeedback(null);
    if (msg.current_z !== undefined) {
      resolved.current_z = msg.current_z;
    }
    else {
      resolved.current_z = 0.0
    }

    return resolved;
    }
};

module.exports = LandingFeedback;
